# Site settings
title: jlehtoma-lablog # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jlehtoma-lablog" # the subpath of your site, e.g. /blog/
url: "https://jlehtoma.github.io" # the base hostname & protocol for your site
include: [ _assets , _projects ]

name : Joona Lehtomäki
email : joona.lehtomaki@gmail.com
github_username: jlehtoma
twitter_username: jlehtoma
website : git@github.com:jlehtoma/jlehtoma-lablog.git

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: # default author for posts (for multi-authoring)
